services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: laravel_app
    ports:
      - "8080:80"
      - "443:443"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: "base64:cCEnneADoBCNQ/1OLZwybplyBgTuydZeNGeM1TlKXOE="
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: laravel_user
      DB_PASSWORD: secret
    volumes:
      - ./:/var/www/html/
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    container_name: laravel_pg
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U laravel_user -d laravel"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
